service: serverless-slack-dad-jokes

app: serverless-slack-dad-jokes
tenant: gableroux

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ca-central-1

functions:
  main:
    handler: handler.main

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: /Users/gableroux/.pyenv/versions/serverless-slack-dad-jokes/bin/python
